### PR TITLE
support for all void-supported architectures

### LINKED ISSUE #3: build images for different architectures
thin images for aarch64 would be helpful for me

### PR DESCRIPTION
**Pull request by selfisekai**
closes #3

### CODE REVIEW

**Comment by the-maldridge** [comment]
Just wanted to drop in and let you know this PR isn't lost in the queue, I just really have not got any time to get to it right now.  You can help me out by helping me understand something in this PR though.  In doing the same thing (setting up arm images from an x86 host) over in -mklive we have to use `qemu-user-static` to ensure that the resultant image has been fully configured.  Can you explain how you're overcoming that problem here?

**Comment by selfisekai** [comment]
@the-maldridge it's using Docker BuildX/Moby BuildKit, which uses QEMU under the hood to emulate each CPU arch (where needed), based on the `platforms` parameter given to the build action

**Comment by the-maldridge** [comment]
I don't think this did quite what you expected.  Can you take a look at [this CI run](https://github.com/void-linux/void-docker/actions/runs/1809750208) and see if you can sus out what happened here?

**Comment by the-maldridge** [comment]
Looks like `ARCH_DIR_PART` didn't get expanded for aarch64 only.  That's as much troubleshooting as I have time for right at this moment, but hopefully that points you at the rough problem area.

**Comment by Johnnynator** [comment]
The  condition for aarch64 can't work since it is bashism. It should be `[ "${ARCH%-musl}"  = " aarch64" ]` 

See e.g. this error line https://github.com/void-linux/void-docker/runs/5102534636?check_suite_focus=true#step:6:149

**Pull request closed without merging**
